global:
  scrape_interval: 15s  # How often to scrape targets (default: 1m)
  evaluation_interval: 15s  # How often to evaluate rules

scrape_configs:
  - job_name: 'kong-admin'
    static_configs:
      - targets: ['34.55.116.90:8001']
